# Q1. Find the total units produced by each product_category.

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("production_analysis_dataset.csv")

df.groupby('product_category')['units_produced'].sum()

product_category
Automotive     9408
Electronics    7491
Furniture      7251
Name: units_produced, dtype: int64

# Q2. Calculate the average profit for each factory.

In [14]:
df.groupby('factory')['profit'].mean().round(2)

factory
Plant_A    18044.38
Plant_B    16973.38
Plant_C    18086.08
Name: profit, dtype: float64

# Q3. Find the total defective_units for each shift.

In [16]:
df.head()
df.groupby('shift')['defective_units'].sum()

shift
Evening    132
Morning    472
Night      471
Name: defective_units, dtype: int64

# Q4. Calculate the average production_time_hr for each supervisor.

In [18]:
df.groupby('supervisor')['production_time_hr'].mean().round(2)

supervisor
S1    7.80
S2    7.45
S3    7.88
S4    7.96
Name: production_time_hr, dtype: float64

# Q5. Find the total energy_consumption_kwh for each factory and shift.

In [20]:
df.groupby(['factory','shift'])['energy_consumption_kwh'].sum()

factory  shift
Plant_A  Evening     3330
         Morning    11144
         Night      12913
Plant_B  Evening     2889
         Morning     7923
         Night       4981
Plant_C  Evening     2214
         Morning     5632
         Night       7363
Name: energy_consumption_kwh, dtype: int64

# Q6. For each product_category, calculate:
total units_produced
average profit
maximum defective_units.

In [26]:
df.groupby('product_category').agg({
    "units_produced":"sum",
    "profit":"mean",
    "defective_units":"max"
})

                  units_produced        profit  defective_units
product_category
Automotive                  9408  18374.722222               34
Electronics                 7491  16945.750000               40
Furniture                   7251  17935.062500               39

# Q7. For each factory, calculate:
mean production_time_hr
median machine_downtime_hr.

In [29]:
df.head()
df.groupby('factory').agg({
    "production_time_hr":"mean",
    "machine_downtime_hr":"median"
})

         production_time_hr  machine_downtime_hr
factory
Plant_A            7.890000                0.945
Plant_B            7.579231                1.070
Plant_C            7.810769                0.850

# Q8. For each shift, compute:
minimum profit
maximum profit
average units_produced.

In [35]:
df.head()
df.groupby('shift').agg({
    "profit":["min","max"],
    "units_produced":"mean"
})

        profit        units_produced
           min    max           mean
shift
Evening  10009  22302     524.857143
Morning  10722  24358     482.090909
Night    12045  24586     470.000000

# Q9. For each supervisor, calculate:
total units_produced
total defective_units.

In [37]:
df.head()
df.groupby('supervisor').agg({
    "units_produced":"sum",
    "defective_units":"sum"
})

            units_produced  defective_units
supervisor
S1                    5231              209
S2                    6069              264
S3                    7418              273
S4                    5432              329

# Q10. Using apply(), calculate the defect rate for each row:
defect_rate=defective_units/units_produced

In [44]:
df["defect_rate"] = df.apply(lambda x: x["defective_units"]/x["units_produced"],axis=1)
df.head()

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118

# Q11. Using groupby().apply(), find the profit range (max − min) for each factory.

In [45]:
df.groupby('factory').apply(lambda x: x["profit"].max()-x["profit"].min())

C:\Users\LJENG\AppData\Local\Temp\ipykernel_7636\3224101717.py:2: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('factory').apply(lambda x: x["profit"].max()-x["profit"].min())

factory
Plant_A    14199
Plant_B    14349
Plant_C    12745
dtype: int64

# Q12. Using groupby().apply(), find the row with maximum units_produced in each product_category.

In [49]:
df.groupby('product_category').apply(lambda x: x.sort_values('units_produced',ascending=False))
df.head(1)

C:\Users\LJENG\AppData\Local\Temp\ipykernel_7636\1906338243.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('product_category').apply(lambda x: x.sort_values('units_produced',ascending=False))

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139

# Q13. Use apply() to create a new column efficiency_score:
efficiency=units_produced/production_time_hr

In [59]:
df['efficiency_score'] = df.apply(lambda x: x['units_produced'] / x['production_time_hr'],axis=1)
df.head()

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate,efficiency_score
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156,91.212121
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559,85.824742
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414,68.005739
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118,53.363229

# Q14. Find how many times each product_category appears in the dataset.

In [62]:
df['product_category'].value_counts()

product_category
Automotive     18
Electronics    16
Furniture      16
Name: count, dtype: int64

# Q15. Count the number of records for each shift.

In [63]:
df.head()
df['shift'].value_counts()

shift
Morning    22
Night      21
Evening     7
Name: count, dtype: int64

# Q16. Find the most frequent supervisor using value_counts().

In [72]:
df.head()
df['supervisor'].value_counts().head(1)

supervisor
S3    15
Name: count, dtype: int64

# Q17. Sort the dataset by profit in descending order.

In [76]:
df.sort_values(by='profit',ascending=False).head()

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate,efficiency_score
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,0.026866,39.273154
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,0.017214,68.562232
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,0.043564,75.373134
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,0.071111,64.562410
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,0.057637,49.571429

# Q18. Sort the dataset by:
•	product_category ascending
•	units_produced descending

In [78]:
df.sort_values(by=["product_category","units_produced"],ascending=[True,False])

,production_id,product_category,factory,shift,supervisor,units_produced,defective_units,production_time_hr,machine_downtime_hr,energy_consumption_kwh,profit,defect_rate,efficiency_score
16,117,Automotive,Plant_B,Evening,S1,690,15,8.12,1.21,1343,10009,0.021739,84.975369
20,121,Automotive,Plant_B,Morning,S2,665,24,7.70,1.07,1182,17177,0.036090,86.363636
48,149,Automotive,Plant_C,Night,S2,662,32,6.51,1.40,1351,21253,0.048338,101.689708
41,142,Automotive,Plant_A,Morning,S2,641,11,7.56,0.93,1216,20168,0.017161,84.788360
0,101,Automotive,Plant_A,Night,S1,627,12,6.58,0.56,1028,12286,0.019139,95.288754
1,102,Automotive,Plant_A,Night,S2,602,32,6.60,0.32,1038,18279,0.053156,91.212121
19,120,Automotive,Plant_C,Night,S2,581,15,7.30,1.33,1233,13470,0.025818,79.589041
15,116,Automotive,Plant_A,Morning,S3,559,11,9.11,0.59,1454,18317,0.019678,61.361142
9,110,Automotive,Plant_B,Morning,S4,505,22,6.70,1.39,1380,24358,0.043564,75.373134
10,111,Automotive,Plant_B,Night,S4,502,34,6.93,0.38,1562,19197,0.067729,72.438672
44,145,Automotive,Plant_A,Evening,S3,479,24,8.96,1.33,1028,10387,0.050104,53.459821
47,148,Automotive,Plant_A,Evening,S1,476,25,7.81,1.48,918,16311,0.052521,60.947503
14,115,Automotive,Plant_B,Night,S2,450,32,6.97,0.20,1539,24349,0.071111,64.562410
35,136,Automotive,Plant_C,Morning,S3,445,15,7.81,0.91,1109,20021,0.033708,56.978233
37,138,Automotive,Plant_B,Night,S4,439,23,8.31,1.13,1008,21263,0.052392,52.827918
29,130,Automotive,Plant_A,Night,S3,379,17,7.39,1.46,1393,22054,0.044855,51.285521
26,127,Automotive,Plant_A,Morning,S1,371,32,7.05,0.80,877,17260,0.086253,52.624113
31,132,Automotive,Plant_A,Night,S1,335,9,8.53,0.51,922,24586,0.026866,39.273154
2,103,Electronics,Plant_A,Night,S4,666,39,7.76,0.78,1084,23261,0.058559,85.824742
7,108,Electronics,Plant_B,Evening,S3,659,9,8.33,0.42,1546,14010,0.013657,79.111645
36,137,Electronics,Plant_C,Night,S2,639,11,9.32,0.37,918,24577,0.017214,68.562232
8,109,Electronics,Plant_A,Morning,S3,627,40,7.16,0.62,1586,22713,0.063796,87.569832
5,106,Electronics,Plant_B,Morning,S2,621,28,8.23,1.12,846,20834,0.045089,75.455650
40,141,Electronics,Plant_B,Morning,S2,489,40,6.94,0.37,1115,15974,0.081800,70.461095
3,104,Electronics,Plant_B,Morning,S3,474,22,6.97,1.44,1144,11674,0.046414,68.005739
38,139,Electronics,Plant_B,Morning,S3,428,8,6.78,0.75,1083,10722,0.018692,63.126844
22,123,Electronics,Plant_B,Night,S4,417,9,9.22,1.32,872,18423,0.021583,45.227766
21,122,Electronics,Plant_A,Morning,S1,415,9,7.51,0.96,1035,19641,0.021687,55.259654
39,140,Electronics,Plant_C,Morning,S1,382,33,8.16,0.76,809,11832,0.086387,46.813725
17,118,Electronics,Plant_A,Night,S1,357,28,9.14,1.28,1114,13923,0.078431,39.059081
18,119,Electronics,Plant_A,Night,S4,343,36,8.95,1.47,1345,22547,0.104956,38.324022
25,126,Electronics,Plant_A,Night,S4,331,30,8.68,1.24,911,14073,0.090634,38.133641
30,131,Electronics,Plant_C,Morning,S2,329,8,8.25,0.85,1343,12579,0.024316,39.878788
46,147,Electronics,Plant_A,Night,S4,314,12,9.13,0.54,1394,14349,0.038217,34.392114
34,135,Furniture,Plant_A,Morning,S3,618,11,6.72,0.48,1071,12170,0.017799,91.964286
32,133,Furniture,Plant_A,Night,S3,617,10,7.76,0.96,1335,15183,0.016207,79.510309
11,112,Furniture,Plant_A,Morning,S1,598,30,7.59,1.50,941,18348,0.050167,78.787879
13,114,Furniture,Plant_C,Evening,S1,583,5,8.54,0.35,1349,22302,0.008576,68.266979
49,150,Furniture,Plant_C,Morning,S3,486,32,6.71,1.06,1138,20209,0.065844,72.429210
4,105,Furniture,Plant_A,Night,S3,476,21,8.92,1.15,1349,12045,0.044118,53.363229
45,146,Furniture,Plant_C,Night,S3,442,9,9.40,0.56,1456,18346,0.020362,47.021277
43,144,Furniture,Plant_A,Morning,S4,436,15,8.86,0.34,839,24067,0.034404,49.209932
33,134,Furniture,Plant_A,Morning,S4,422,21,7.69,1.07,1107,17491,0.049763,54.876463
23,124,Furniture,Plant_A,Evening,S4,409,39,6.90,1.42,1384,19440,0.095355,59.275362
24,125,Furniture,Plant_C,Morning,S1,397,11,6.79,0.76,1233,16735,0.027708,58.468336
42,143,Furniture,Plant_C,Night,S2,390,31,6.57,1.16,1140,22818,0.079487,59.360731
12,113,Furniture,Plant_C,Evening,S3,378,15,8.88,0.75,865,16304,0.039683,42.567568
6,107,Furniture,Plant_B,Morning,S3,351,29,7.33,1.03,1173,12664,0.082621,47.885402
27,128,Furniture,Plant_A,Morning,S4,347,20,7.00,0.83,1018,24166,0.057637,49.571429
28,129,Furniture,Plant_C,Night,S4,301,29,7.30,1.22,1265,14673,0.096346,41.232877