# PB UNIT - 4 QUESTIONS
- SIMPLE LINEAR REGRESSION PROGRAMS - 215,216,220,221,223
- MULTIPLE LINEAR REGRESSION PROGRAMS 217,224,225,226,227,229
- POLYNOMIAL REGRESSION PROGRAMS - 218,219,230
### 215

For x = np.array([5, 15, 25, 35, 45, 55]) and y = np.array([5, 20, 14, 32, 22, 38]), apply simple linear regression using scikit learn library and calculate calculate R squared, coeficient and intercept. Predict the y values for x = np.arange(5). (Don't split data for training/testing)

---

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [2]:
# Define feature and target
x = np.array([5, 15, 25, 35, 45, 55]).reshape(-1,1) 
y = np.array([5, 20, 14, 32, 22, 38])

In [3]:
# create model
model = LinearRegression()

In [4]:
# fit the model
model.fit(x,y)

LinearRegression()

In [5]:
# Print r2_score,slope and intercept
print(model.score(x,y))
slope = model.coef_[0]
intercept = model.intercept_
print(f'The linear regression equation is y = {intercept:.2f}+{slope:.2f}*x')

0.715875613747954
The linear regression equation is y = 5.63+0.54*x

In [6]:
model.predict(np.arange(5).reshape(-1,1))

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

### 216

Given a dataset with 'SAT' scores as independent variables and 'GPA' as the dependent variable, calculate R squared, coeficient and intercept using linear regression and scikitlearn library. (Don't split data for training/testing)

---

In [7]:
df = pd.read_csv("SATGPA.csv")

In [8]:
x2 = df[['SAT']]
y2 = df['GPA']

In [9]:
model2 = LinearRegression()

In [10]:
model2.fit(x2,y2)

LinearRegression()

In [11]:
print(model2.intercept_)
print(model2.coef_[0])

0.2750402996602803
0.001655688050092814

In [12]:
print(model.score(x2,y2))

-13726555.584961817

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2742: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(

### 217

Given a real estate price size year dataset, implement multiple linear regression using scikitlearn library. Using the model, make a prediction about an apartment price with size 750 sq.ft. for 2009.Also Calculate R squared, coeficient and intercept. (Don't split data for training/testing)

---

In [13]:
import pandas as pd

In [14]:
data = pd.DataFrame({
    'size' : [2104,1600,2400,1416,3000],
    'year' : [2003,1977,2001,1995,2000],
    'price' : [399900,329900,369000,232000,539900]
})

In [15]:
data

   size  year   price
0  2104  2003  399900
1  1600  1977  329900
2  2400  2001  369000
3  1416  1995  232000
4  3000  2000  539900

In [16]:
x = data[['size','year']]
y = data['price']

In [17]:
m1 = LinearRegression()

In [18]:
m1.fit(x,y)

LinearRegression()

In [19]:
slope = m1.coef_[0]
intercept = m1.intercept_
print("The intercept is: " ,intercept)
print("Slope is:",slope)
print(m1.score(x,y))

The intercept is:  4778064.714300399
Slope is: 187.88485815154039
0.9110630594451152

In [20]:
newdata = pd.DataFrame({
    'size':[750],
    'year':[2009]
})

prediction = m1.predict(newdata)
print("Prdeiction for 750 sqft house with 2009 year is",prediction[0])

Prdeiction for 750 sqft house with 2009 year is 86549.5177951986

### 218 
```
predict salary based on position of 6.5 using polynomial regression with the degree of 3 and scikit learn library for the given dataset.

In [21]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression

df = pd.read_csv("Position_Salaries.csv")
df.head()

# define features and target
x = df[['Level']]
y = df['Salary']

# create polynomial features
poly = PolynomialFeatures(degree=3)
# transform x variable
x_poly = poly.fit_transform(x)

model = LinearRegression()

model.fit(x_poly,y)

print("Slope:",model.coef_)
print("Intercept:",model.intercept_)

## Prediction
level = np.array([[6.5]])
level_poly = poly.fit_transform(level)
predicted_salary = model.predict(level_poly)
print(predicted_salary)

Slope: [     0.         180664.33566432 -48548.95104895   4120.04662005]
Intercept: -121333.33333330567
[133259.46969697]

### 219
```
For x = np.arange(0, 30) and y = np.array([3, 4, 5, 7, 10, 8, 9, 10, 10, 23, 27, 44, 50, 63, 67, 60, 62, 70, 75, 88, 81, 87, 95, 100, 108, 135, 151, 160, 169, 179]), apply polynomial regression using scikit learn library and calculate R squared, coeficient and intercept. Predict the y values for x = np.arange(5). (Don't split data for training/testing)

In [22]:
x = np.arange(0, 30).reshape(-1,1)
y = np.array([3, 4, 5, 7, 10, 8, 9, 10, 10, 23, 27, 44, 50, 63, 67, 60, 62, 70, 75, 88, 81, 87, 95, 100, 108, 135, 151, 160, 169, 179])

In [23]:
poly = PolynomialFeatures(degree=3)
x_poly = poly.fit_transform(x)

model = LinearRegression()

model.fit(x_poly,y)

LinearRegression()

In [24]:
print("R-Square:",model.score(x_poly,y))
print("Coefficient:",model.coef_)
print("Intercept:",model.intercept_)

R-Square: 0.9760588291456355
Coefficient: [ 0.          3.38954229 -0.03098624  0.00447358]
Intercept: -3.195869990226825

In [25]:
w = np.arange(5).reshape(-1,1)
w_poly = poly.transform(w)
prediction = model.predict(w_poly)
print(prediction)

[-3.19586999  0.16715964  3.49505824  6.81466728 10.15282821]

### 220

Write a program to make a model based on linear regression for the following dataframe created from a csv file named “Package.csv” of x and y which follows equation y = a + bx. Write a program which can predict value of y based on any value of x, also write code to find value of a and b in above equation.
Given Data in csv file:

| cgpa | package |
| ---- | ------- |
| 6.89 | 3.26    |
| 5.12 | 1.98    |
| 7.82 | 3.25    |
| 7.42 | 3.67    |
| 6.94 | 3.57    |
| 7.89 | 2.99    |
| 6.73 | 2.60    |
| 6.75 | 2.48    |
| 6.09 | 2.31    |
| 8.31 | 3.51    |
| 5.32 | 1.86    |
| 6.61 | 2.60    |
| 8.94 | 3.65    |
| 6.93 | 2.89    |
| 7.73 | 3.42    |

---

In [26]:
df = pd.read_excel("package.xlsx")
df.head()

   cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [27]:
x = df[['cgpa']]
y = df['package']

In [28]:
model = LinearRegression()

In [29]:
model.fit(x,y)

LinearRegression()

In [30]:
a = model.intercept_
b = model.coef_[0]

In [31]:
print(f'The linear regression equation is y = {a:.2f}+{b:.2f}*x')

The linear regression equation is y = -0.57+0.50*x

In [32]:
print(model.score(x,y))

0.7346579118964653

### 221

Write a program to make a model based on linear regression for the following dataframe created from a csv file named “data.csv” of x1 and y which follows equation y = a+bx1. Write a program which can predict value of y based on any value of x, also write code to find value of a and b in above equation.
Given Data in csv file:

| y   | x1 |
| --- | -- |
| 140 | 60 |
| 155 | 62 |
| 159 | 67 |
| 179 | 70 |
| 192 | 71 |
| 200 | 72 |
| 212 | 75 |
| 215 | 78 |

---

### 222

Write a program to create a Model using linear regression to predict the price of house using the csv file provided named “Housing.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

### 223

Write a program to create a Model using linear regression to predict the student scores using the csv file provided named “student_scores.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

In [33]:
df = pd.read_csv("student_scores.csv")
df.head(2)

   Hours  Scores
0    2.5      21
1    5.1      47

In [34]:
x = df[['Hours']]
y = df['Scores']

In [35]:
model = LinearRegression()

In [36]:
model.fit(x,y)

LinearRegression()

In [37]:
print(model.score(x,y))
print(model.coef_[0])
print(model.intercept_)
prediction = model.predict(x)

0.9529481969048356
9.775803390787468
2.48367340537321

In [38]:
print(prediction)

[26.92318188 52.3402707  33.76624426 85.57800223 36.69898527 17.14737849
 92.4210646  56.25059205 83.62284155 28.87834256 77.75735951 60.16091341
 46.47478866 34.74382459 13.23705714 89.48832358 26.92318188 21.05769985
 62.11607409 74.8246185  28.87834256 49.40752968 39.63172629 69.9367168
 78.73493985]

In [39]:
print(mean_squared_error(y,prediction))

28.882730509245466

### 224

Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named “petrol_consumption.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

In [40]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
df = pd.read_csv("petrol_consumption.csv")

In [41]:
df.head()

,Petrol_tax,Average_income,Paved_Highways,Population_Driver_licence(%),Petrol_Consumption
0,9.0,3571,1976,0.525,541
1,9.0,4092,1250,0.572,524
2,9.0,3865,1586,0.580,561
3,7.5,4870,2351,0.529,414
4,8.0,4399,431,0.544,410

In [42]:
x = df[['Petrol_tax','Average_income','Paved_Highways','Population_Driver_licence(%)']]
y = df['Petrol_Consumption']

In [43]:
model_1 = LinearRegression()

In [44]:
model_1.fit(x,y)

LinearRegression()

In [45]:
print(f"Coefficient is: {model_1.coef_[0]}")
print(f"Intercept is: {model_1.intercept_}")
print(f'Mean squared error is: {mean_squared_error(y,prediction1)}')
prediction1 = model_1.predict(x)
print(f"Predicted values: {prediction1}")

Coefficient is: -34.79014916443289
Intercept is: 377.2911464736735

NameError: name 'prediction1' is not defined

### 225

Write a program to create a Model using linear regression to predict the gas consumption using the csv file provided named “FuelConsumptionCo2.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error. (Wherever required remove null values, convert categorical data into numeric data)

---

In [47]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [48]:
df = pd.read_csv("FuelConsumptionCo2.csv")
df.head(2)

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221

In [49]:
df = pd.get_dummies(df)
df.head()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS,MAKE_ACURA,MAKE_ASTON MARTIN,...,TRANSMISSION_AV6,TRANSMISSION_AV7,TRANSMISSION_AV8,TRANSMISSION_M5,TRANSMISSION_M6,TRANSMISSION_M7,FUELTYPE_D,FUELTYPE_E,FUELTYPE_X,FUELTYPE_Z
0,2014,2.0,4,9.9,6.7,8.5,33,196,True,False,...,False,False,False,False,False,False,False,False,False,True
1,2014,2.4,4,11.2,7.7,9.6,29,221,True,False,...,False,False,False,False,True,False,False,False,False,True
2,2014,1.5,4,6.0,5.8,5.9,48,136,True,False,...,False,True,False,False,False,False,False,False,False,True
3,2014,3.5,6,12.7,9.1,11.1,25,255,True,False,...,False,False,False,False,False,False,False,False,False,True
4,2014,3.5,6,12.1,8.7,10.6,27,244,True,False,...,False,False,False,False,False,False,False,False,False,True

In [50]:
x = df.drop(columns=['CO2EMISSIONS'],axis=1)
y = df['CO2EMISSIONS']

In [51]:
print(x.shape)
print(y.shape)

(1067, 751)
(1067,)

In [52]:
model = LinearRegression()

In [53]:
model.fit(x,y)

LinearRegression()

In [ ]:
print(f'Coefficient is: {model.coef_}')
print(f'Intercept is: {model.intercept_}')
prediction = model.predict(x)
print(f'Mean squared error is: {mean_squared_error(y,prediction)}')

### 226

For the given RealEstate csv, write a python program satisfying following tasks to demonstrate application of machine learning through multiple linear regression as follows –

Dataset: RealEstate.csv
ML Library to be used: scikit-learn
Dependent variable: 'Y house price of unit area'
Independent variables: 'X1 transaction date', 'X2 house age', 'X3 distance to the nearest MRT station', 'X4 number of convenience stores', 'X5 latitude' and 'X6 longitude'

1. Import required libraries.
2. Load RealEstate dataset, create a dataframe and check datatypes of its attributes using appropriate method.
3. Remove ‘No’ column from the dataframe.
4. Check for any null values in features using appropriate method.
5. Create feature variables x and y as given above.
6. Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
7. Create and fit regression model using appropriate method.
8. Use testing set created in step 6 to find and print the prediction of the outcome.
9. Find and print coefficient and mean squared error of the regression model.

---

In [60]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split

In [61]:
df = pd.read_csv("RealEstate.csv")
df.head(2)

,No,X1 transaction date,X2 house age,X3 distance to the nearest MRT station,X4 number of convenience stores,X5 latitude,X6 longitude,Y house price of unit area
0,1,2012.917,32.0,84.87882,10,24.98298,121.54024,37.9
1,2,2012.917,19.5,306.59470,9,24.98034,121.53951,42.2

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 414 entries, 0 to 413
Data columns (total 8 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   No                                      414 non-null    int64
 1   X1 transaction date                     414 non-null    float64
 2   X2 house age                            414 non-null    float64
 3   X3 distance to the nearest MRT station  414 non-null    float64
 4   X4 number of convenience stores         414 non-null    int64
 5   X5 latitude                             414 non-null    float64
 6   X6 longitude                            414 non-null    float64
 7   Y house price of unit area              414 non-null    float64
dtypes: float64(6), int64(2)
memory usage: 26.0 KB

In [64]:
df.drop(columns=['No'],inplace=True)

In [66]:
# 4. Check for any null values in features using appropriate method.
print(df.isnull().sum())

X1 transaction date                       0
X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64

In [71]:
# Create feature variables x and y as given above.
x = df[['X1 transaction date','X2 house age','X3 distance to the nearest MRT station','X4 number of convenience stores','X5 latitude','X6 longitude']]
y = df['Y house price of unit area']

In [68]:
# Create training and testing sets of feature variables with 70% of data for training and with random state of 110.
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=110)

In [72]:
# Create and fit regression model using appropriate method.
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [75]:
# Use testing set created in step 6 to find and print the prediction of the outcome.
y_pred = model.predict(x_test)
print(y_pred)

[203.57430407 400.47653551 218.21547482 255.81737942 294.70257771
 237.11484037 165.78948036 389.40122439 157.11813533 323.60946133
 300.71833194 249.31232569 211.47489575 306.24987548 252.39626433
 295.34937325 255.02469565 265.38013136 267.93252888 304.20607145
 353.37312192 210.68268087 246.81878252 307.11009258 232.67419967
 214.20457787 191.37440543 233.10923746 329.72520166 386.75768854
 296.56747882 285.95853652 133.76090492 176.08013761 181.06960338
 256.25155624  94.88073028 224.79587538 185.47038058 347.45772006
 386.86402194 255.72245981 230.34510416 230.65464727 342.5214293
 319.23722416 190.84664575 190.53679106 306.62671493 209.76381796
 369.48683457 210.82678287 224.04959775 177.17162614 276.76071373
 384.75024061 301.31203904 184.15335425 189.52915655 304.37846182
 345.50978296 372.95680448 265.46409908 286.34794807 301.92741459
 261.2560298  175.796128   384.70039857 197.0629988  279.38960286
 216.69319463 290.26963851 157.9941561  268.51338658 221.16960631
 183.68490995 182.67746206 256.52799372 266.9423458  240.01698512
 319.15668856 217.92402321 378.04489215 208.64019674 202.624644
 298.72472287 252.64573184  36.87240171 264.37527193 201.62919119
 165.66229174 205.14269853 273.52286877 311.14401273 248.02469565
 424.75997231 188.92940938 213.92900758 239.30307167 287.96571193
 213.00821379 379.82341551 170.05650983 283.72771736 219.92038886
 288.06869356 138.06159695 251.14398534 294.70257771 373.46307312
 268.1956667  210.82678287 189.96624489  68.11321226 293.14712705
 174.12446302 162.67168173 171.93344    174.88069366 294.70257771
 284.84631223 286.47617356 179.27279752 191.29904354 237.57936825
 255.61271342 193.7952928  238.0742709  229.85872218 224.79587538
 185.8314882  206.89125929 218.12148806 373.88459132 178.88078298
 353.37312192 222.56476902 258.76798985 196.36879148 252.26253993
 197.7142555  264.690586   159.75636998 232.38473554 297.84708041
 285.79487484 209.63812606 190.46522851 140.85782478 301.74225701
 300.0044723  212.75395173 361.49154258 277.7214994  100.95461685
 199.10317985 254.03598346 265.87904887 167.29187579 413.69507596
 178.08790092 242.03810215 251.0442625  339.14811597 226.58546881
 277.76584289 200.04115648 274.19690645 366.88400059 338.89642146
 329.14239124 210.48039794 353.33001588 300.71833194 173.10675299
 276.66192428  82.31695223 261.72133184 325.27479834 290.34280617
 253.55526532 279.4551477  253.28775775 287.76374983 195.73092075
 275.00078956 323.07423985 213.57068477 202.36165244 288.47598974
 349.77110349 313.34485173 191.15188824 181.06960338 193.08059628
 263.70787408 259.16209835 207.69370379 209.76381796 329.72520166
 293.40497043 190.12845349 422.46927428 201.48987679 253.45934445
 184.15335425 274.03206555 281.0804803  200.97712566 210.80596585
 226.48498785 268.09688122 259.14242265 205.58986089 212.4277849
 210.82678287 247.84148017 208.00083171 211.69112049 353.33001588
 204.35043621 198.80399404 287.38259001 232.38473554 248.99014302
 232.12937511 233.80370472 199.24439583 252.69106696 286.86871896
 239.95337864 178.27409559 273.47515117 271.84670252 375.86767692
 348.52796106 356.91072657 179.61850938 320.16515911 251.07542823
 280.18405883 316.29742229 289.86119308 266.38774002 373.28716749
 246.26574287 249.75486943 276.86951182 213.62955618 290.4814728
 378.72628554 218.59128308 358.18135677 264.63335553 388.41882916
 327.26932345 243.39722929 273.47515117 176.40892065 218.12141196
 175.30699418 341.61566152 224.24599932 277.07386906 211.33227656
 195.49275874 278.37891482 350.24942939 184.15335425 261.63155624
 248.98355893 245.99874727 200.57778335 204.09095226 292.13435457
 179.02411816 212.71255201 179.0391844  116.10324031 259.8491066
 190.5315557  267.4925374  120.36274602 220.21329681 276.4697648
 428.01152855 242.62171927 218.24485874 196.91986239 204.04645277
 186.92301016 282.30945254 209.76381796 242.56108456 274.07838289
 259.00903054 370.66998412 217.19283384 265.87707347 212.82321048
 265.48588342 227.25737778 383.87776579 408.76426337 259.65964894
 371.02165239 167.51812442 229.33884742 185.94359236 222.41932382
 407.19476897 255.02469565 239.4649829  240.64341064 260.29107173
 294.70257771 162.72284033 184.76979084 233.32558539 296.82904554
 293.40497043]

In [ ]:
# Find and print coefficient and mean squared error of the regression model.
print("Coefficient is:",model.coef_)
print("Mean squared error:",mean_squared_error(y_test,y_pred))
print(r2_score(y_test,y_pred))

### 227

Write a program to create a Model using linear regression to predict the charges of insurance using the csv file provided named “insurance.csv”. Do the required process in the data before making a model. Find predicted values, co-efficients, intercept and mean squared error.

---

In [80]:
df = pd.read_csv("insurance.csv")

In [81]:
df.head(2)

   age     sex   bmi  children smoker     region  expenses
0   19  female  27.9         0    yes  southwest  16884.92
1   18    male  33.8         1     no  southeast   1725.55

In [86]:
x = df[['age','bmi','children']]
y = df['expenses']

In [87]:
model = LinearRegression()

In [88]:
model.fit(x,y)

LinearRegression()

In [89]:
print(model.coef_)
print(model.intercept_)

[239.96255473 332.52157882 543.04360565]
-6929.314453097686

In [90]:
prediction = model.predict(x)
print(prediction)

[ 6907.32613573  9172.28450167 12391.97999719 ...  9660.05779036
  6688.95592967 17384.77932889]

In [91]:
print("MSE:",mean_squared_error(y,prediction))

MSE: 128932346.53522764

### 228

Write a program to create a Model using linear regression to predict the wine quality using the csv file provided named “winequality.csv”. Do the required process in the data before making a model.

If you find any null value in “winequality.csv” then replace null value with mean value of respected columns.
Find co-efficient, intercept and mean squared error.

Also Predict the quality of red wine for the following data:

fixed acidity: 8
volatile acidity: 0.4
citric acid: 0.40
residual sugar: 15
chlorides: 0.048
free sulfur dioxide: 40
total sulfur dioxide: 150
density: 0.99
pH: 3
sulphates: 0.45
alcohol: 10.5

---

In [99]:
df = pd.read_csv("winequality.csv")
df.head(2)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,Id
0,7.4,0.70,0.0,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,0
1,7.8,0.88,0.0,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,1

In [117]:
x = df.drop(columns=['quality','Id'])
y = df['quality']

In [118]:
model = LinearRegression()

In [119]:
model.fit(x,y)

LinearRegression()

In [120]:
print(model.coef_)
print(model.intercept_)

[ 2.29746331e-02 -1.12910200e+00 -1.31862721e-01  1.35116748e-02
 -1.70816059e+00  2.36938156e-03 -2.78491532e-03 -1.74492955e+01
 -4.08202784e-01  8.75200141e-01  2.80142992e-01]
21.54947030097066

In [121]:
prediction = model.predict(x)
print("MSE:",mean_squared_error(y,prediction))

MSE: 0.40598198111589573

In [122]:
print(model.predict([[8,0.4,0.4,15,0.048,40,150,0.99,3,0.45,10.5]]))

[5.86253341]

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

### 229

Consider variables x and y created from a pandas dataframe “car.csv”.
Create new column named “Age_car” (Age_car=2023-year)

For multiple linear regression problem, x contains the independent variables (Age_car, Driven_kms, Fuel_Type, Selling_type, Transmission) and y contains the dependent (Selling_Price) variable which is to be predicted.

Write a Python program to split x and y into training and testing datasets with a 20% split. Then create a multiple linear regression model using the training data and print its coefficients, intercept and mean squared error.

---

In [174]:
df = pd.read_csv('car.csv')
df.drop('Car_Name',inplace=True,axis=1)

In [175]:
df['Age_car'] = 2023 - df['Year']

In [176]:
df.head(2)

,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,10

In [177]:
df = pd.get_dummies(df)

### 230

Write a python program for following tasks -

Make sure all the required libraries are imported at the beginning of the Jupyter Notebook.

a) Load the windpower dataset into the notebook.
b) Check records for any missing values and remove them permanently using appropriate method.
c) Treat windspeed as the independent variable and power as the dependent variable. Split the dataset into training (75%) and testing (25%) sets using random state of 42.
d) Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.
e) Predict power values on the test set and print the Mean Squared Error (MSE) and R² score (coefficient of determination) for each polynomial degree.
f) Plot actual vs. predicted power values for all polynomial degrees on the same graph for comparison and label the plot accordingly.
g) Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.
h) Print the coefficients and intercept for each trained polynomial regression model.
i) Use each model to predict power output for wind speeds of 5, 10, 15, and 20 m/s, and print the predictions.

---

In [ ]:
df = pd.read_csv("windpower.csv")
df = df.dropna()

In [ ]:
print(df.to_string())

In [ ]:
x = df[['Wind speed (m/s)']]
y = df['Power (kW)']

In [ ]:
# Split the dataset into training (75%) and testing (25%) sets using random state of 42.
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=42)

In [ ]:
#  d) Use scikit-learn to train polynomial regression models of degrees 3, 4, 5, and 6.
# e) Predict power values on the test set and print the Mean Squared Error (MSE) and R² score (coefficient of determination) for each polynomial degree.
from sklearn.metrics import mean_squared_error,r2_score
import seaborn as sns
import matplotlib.pyplot as plt
givendegress = [3,4,5,6]
mse_values = []
r2_scores = []

# f) Plot actual vs. predicted power values for all polynomial degrees on the same graph for comparison and label the plot accordingly.
windspeeds = np.array([[5],[10],[15],[20]])
windprediction = {}

plt.style.use('ggplot')
plt.figure(figsize=(12,8))
plt.title("Polynomial regression of windpower")
plt.scatter(x,y,color='k',label='truevalues')

for degree in givendegress:
    poly = PolynomialFeatures(degree=degree)
    x_train_poly = poly.fit_transform(x_train)
    x_test_poly = poly.fit_transform(x_test)
    model = LinearRegression()
    model.fit(x_train_poly,y_train)
    predictions = model.predict(x_test_poly)
    mse = mean_squared_error(y_test,predictions)
    r2 = r2_score(y_test,predictions)
    mse_values.append(mse)
    r2_scores.append(r2)
    print(f"Result for {degree} polynomial regression")
    print(f"Coefficients: {model.coef_}")
    print(f"Intercepts: {model.intercept_}")
    print(f"Mean squared error: {mse:.2f}")
    print(f"Coefficient of Determination:{r2:.2f}")

    plt.plot(x_test,predictions,'x',label=f'predictedvalues for {degree}')
    print("__________________________________________")
    windspeedpoly = poly.fit_transform(windspeeds)
    powerpredict = model.predict(windspeedpoly)
    windprediction[degree] = powerpredict
plt.xlabel("Windspeed")
plt.ylabel("Power")
plt.legend()
plt.show()

In [ ]:
print(windprediction)

In [ ]:
# g) Create a plot showing MSE vs. polynomial degree. Which degree has the lowest MSE? Write in the comment.
# the sixth degree has the lowest mes of all
plt.figure(figsize=(8,6))
plt.plot(givendegress,mse_values,marker='o',linestyle='-',color='b')
plt.title("MSE vs DEGREE")
plt.xlabel("Degree")
plt.ylabel("MSE")
plt.grid(True)
plt.show()